<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH37swhx\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH37swhx/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerH37swhx.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerH37swhx\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerH37swhx\appDevDebugProjectContainer(array(
    'container.build_hash' => 'H37swhx',
    'container.build_id' => '912f0dba',
    'container.build_time' => 1541286864,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerH37swhx');
